import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D, Inria_Serif } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const k2d = K2D({
  variable: '--font-k2d',
  subsets: ["latin"],
  weight: ['400', '500']
})

const inria_serif = Inria_Serif({
  variable: "--font-inria_serif",
  subsets: ["latin"],
  weight: ['400']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${k2d.variable} ${inria_serif.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#F0F8FD]">
         {children}
        </div>
      </body>
    </html>
  );
}
